on:
  push:
 
jobs:
  test_builder:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: almalinux
            tag: 8.9-20231124
          - image: almalinux
            tag: 9.3-20231124
          - image: rockylinux
            tag: '8.9.20231119'
          - image: rockylinux
            tag: '9.3.20231119'
          - image: debian
            tag: bullseye
          - image: debian
            tag: bookworm
          - image: ubuntu
            tag: focal
          - image: ubuntu
            tag: jammy
          - image: ubuntu
            tag: mantic
          - image: ubuntu
            tag: noble
    container:
      image: ${{ matrix.image }}:${{ matrix.tag }}
    steps:
      - uses: actions/checkout@v4
      - run: sh environment_builder.sh
  test_builder_with_curl:
    runs-on: ubuntu-latest
    steps:
      - run: curl https://raw.githubusercontent.com/masa-orca/mandantory-cli-environment-builder/main/environment_builder.sh -o environment_builder.sh
      - run: sudo sh ./environment_builder.sh
